global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'mock_services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['web:8080']
    scheme: 'http'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']  
